# Generated by Django 6.0.3 on 2026-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Wholesaler Paybill or Till Number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shortcode_type',
            field=models.CharField(blank=True, choices=[('PAYBILL', 'Paybill'), ('TILL', 'Till Number (Buy Goods)')], max_length=10, null=True),
        ),
    ]
