# Generated by Django 6.0.3 on 2026-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_mpesa_shortcode_user_shortcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_wholesaler',
            field=models.BooleanField(default=False, help_text='Admin toggles this to True after verifying business docs.'),
        ),
    ]
