# Generated by Django 6.0.3 on 2026-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified_wholesaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_address',
            field=models.TextField(blank=True, help_text='Physical location for order pickups', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
